import AppKit
import CryptoKit
import Foundation
import UniformTypeIdentifiers

struct ClipboardPasteboardReader {
    private let maxRepresentationSize = 10 * 1024 * 1024
    private let maxCaptureSize = 25 * 1024 * 1024
    private let skippedTypeIdentifiers: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.lastpass.LastPass",
        "com.bitwarden.desktop",
    ]
    private let excludedBundleIdentifiers: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.lastpass.LastPass",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
    ]

    func readCapture(from pasteboard: NSPasteboard = .general) -> ClipboardCapture? {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else {
            return nil
        }

        let sourceApplication = NSWorkspace.shared.frontmostApplication
        if let bundleIdentifier = sourceApplication?.bundleIdentifier,
           excludedBundleIdentifiers.contains(bundleIdentifier) {
            return nil
        }

        guard !pasteboardItems.contains(where: { containsSkippedMarker($0) }) else {
            return nil
        }

        var clipboardItems: [ClipboardItem] = []
        var totalByteCount = 0

        for (index, pasteboardItem) in pasteboardItems.enumerated() {
            var representations: [ClipboardRepresentation] = []
            for pasteboardType in pasteboardItem.types {
                let typeIdentifier = pasteboardType.rawValue
                guard !skippedTypeIdentifiers.contains(typeIdentifier),
                      let data = pasteboardItem.data(forType: pasteboardType),
                      !data.isEmpty,
                      data.count <= maxRepresentationSize else {
                    continue
                }

                totalByteCount += data.count
                guard totalByteCount <= maxCaptureSize else {
                    return nil
                }

                let canIndexSafely = Self.canIndexSafely(typeIdentifier: typeIdentifier)
                representations.append(ClipboardRepresentation(
                    typeIdentifier: typeIdentifier,
                    data: data,
                    canIndexSafely: canIndexSafely
                ))
            }

            guard !representations.isEmpty else {
                continue
            }

            let kind = Self.kind(for: representations)
            clipboardItems.append(ClipboardItem(
                id: UUID(),
                index: index,
                kind: kind,
                title: Self.title(for: representations, kind: kind),
                subtitle: Self.subtitle(for: representations, kind: kind),
                representations: Self.sortedRepresentationsForRestore(representations)
            ))
        }

        guard !clipboardItems.isEmpty else {
            return nil
        }

        let exactHash = Self.exactHash(for: clipboardItems)
        let searchableText = Self.searchableText(for: clipboardItems)
        let semanticHash = Self.semanticHash(for: clipboardItems, fallback: exactHash)
        let primaryKind = clipboardItems.first?.kind ?? .other
        let now = Date()

        return ClipboardCapture(
            id: UUID(),
            createdAt: now,
            lastCopiedAt: now,
            sourceBundleIdentifier: sourceApplication?.bundleIdentifier,
            sourceApplicationName: sourceApplication?.localizedName,
            changeCount: pasteboard.changeCount,
            items: clipboardItems,
            primaryKind: primaryKind,
            displayTitle: Self.displayTitle(for: clipboardItems, searchableText: searchableText),
            searchableText: searchableText,
            exactHash: exactHash,
            semanticHash: semanticHash,
            copyCount: 1,
            isPinned: false,
            totalByteCount: totalByteCount
        )
    }

    private func containsSkippedMarker(_ item: NSPasteboardItem) -> Bool {
        item.types.contains { skippedTypeIdentifiers.contains($0.rawValue) }
    }

    private static func canIndexSafely(typeIdentifier: String) -> Bool {
        guard let type = UTType(typeIdentifier) else {
            return false
        }
        return type.conforms(to: .text) ||
            type.conforms(to: .url) ||
            type.conforms(to: .fileURL) ||
            type.conforms(to: .html) ||
            type.conforms(to: .rtf)
    }

    private static func kind(for representations: [ClipboardRepresentation]) -> ClipboardContentKind {
        if representations.contains(where: { $0.isFileURL }) {
            return .file
        }
        if representations.contains(where: { $0.isPDF }) {
            return .pdf
        }
        if representations.contains(where: { $0.isImage }) {
            return .image
        }
        if representations.contains(where: { representation in
            guard representation.isPlainText, let text = representation.decodedText else { return false }
            return URL(string: text.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil
        }) {
            return .link
        }
        if representations.contains(where: { $0.isRichText }) {
            return .richText
        }
        if representations.contains(where: { $0.isPlainText }) {
            return .text
        }
        return .other
    }

    private static func title(
        for representations: [ClipboardRepresentation],
        kind: ClipboardContentKind
    ) -> String {
        if kind == .file {
            let fileNames = representations
                .compactMap(\.fileURL)
                .map(\.lastPathComponent)
                .filter { !$0.isEmpty }
            if !fileNames.isEmpty {
                return fileNames.joined(separator: ", ")
            }
        }

        if let text = representations.compactMap(\.decodedText).first {
            let normalized = text
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !normalized.isEmpty {
                return String(normalized.prefix(90))
            }
        }

        if let firstType = representations.first?.typeIdentifier {
            return firstType
        }

        return kind.title
    }

    private static func subtitle(
        for representations: [ClipboardRepresentation],
        kind: ClipboardContentKind
    ) -> String {
        let typeCount = representations.count
        let bytes = ByteCountFormatter.string(
            fromByteCount: Int64(representations.reduce(0) { $0 + $1.size }),
            countStyle: .file
        )
        return "\(kind.title) · \(typeCount) type\(typeCount == 1 ? "" : "s") · \(bytes)"
    }

    private static func displayTitle(
        for items: [ClipboardItem],
        searchableText: String
    ) -> String {
        if let firstTitle = items.first?.title, !firstTitle.isEmpty {
            return firstTitle
        }
        if !searchableText.isEmpty {
            return String(searchableText.prefix(90))
        }
        return "\(items.count) item\(items.count == 1 ? "" : "s")"
    }

    private static func searchableText(for items: [ClipboardItem]) -> String {
        items.flatMap { item in
            item.representations.compactMap { representation -> String? in
                guard representation.canIndexSafely else { return nil }
                if representation.isFileURL {
                    return representation.fileURL?.lastPathComponent
                }
                return representation.decodedText
            }
        }
        .joined(separator: "\n")
        .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func semanticHash(for items: [ClipboardItem], fallback: String) -> String {
        let semanticText = searchableText(for: items)
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
        guard !semanticText.isEmpty else {
            return fallback
        }
        return sha256Hex(Data(semanticText.utf8))
    }

    private static func exactHash(for items: [ClipboardItem]) -> String {
        var hasher = SHA256()
        for item in items.sorted(by: { $0.index < $1.index }) {
            hasher.update(data: Data("item:\(item.index)".utf8))
            for representation in item.representations.sorted(by: { $0.typeIdentifier < $1.typeIdentifier }) {
                hasher.update(data: Data(representation.typeIdentifier.utf8))
                hasher.update(data: Data("\(representation.data.count)".utf8))
                hasher.update(data: representation.data)
            }
        }
        let digest = hasher.finalize()
        return digest.map { String(format: "%02x", $0) }.joined()
    }

    private static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private static func sortedRepresentationsForRestore(
        _ representations: [ClipboardRepresentation]
    ) -> [ClipboardRepresentation] {
        representations.sorted { lhs, rhs in
            restorePriority(lhs) < restorePriority(rhs)
        }
    }

    private static func restorePriority(_ representation: ClipboardRepresentation) -> Int {
        if representation.isFileURL { return 0 }
        if representation.isPDF { return 1 }
        if representation.isImage { return 2 }
        if representation.isRichText { return 3 }
        if representation.isPlainText { return 4 }
        return 10
    }
}
